
title: XDAG | A new DAG-based cryptocurrency
description: A new DAG-based cryptocurrency
baseurl: ""
url: ""

paginate: 6
paginate_path: 'news/:num'

plugins:
  - jekyll-paginate

exclude: ['Gemfile', 'Gemfile.lock', 'package.json', 'package-lock.json', 'vendor']


